# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 11:15
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', accounts.models.PhoneNumberField(blank=True, max_length=12, validators=[accounts.models.phonenumber_validator, accounts.models.phonenumber_validator, accounts.models.phonenumber_validator, accounts.models.phonenumber_validator, accounts.models.phonenumber_validator])),
                ('device_type', models.CharField(choices=[('a', 'ANDROID'), ('i', 'IOS')], default='ANDROID', max_length=10)),
                ('join_path', models.CharField(default='general', max_length=20)),
                ('attend_count', models.IntegerField(blank=True, default=0)),
                ('penalty_count', models.IntegerField(blank=True, default=0)),
                ('user_image', models.ImageField(blank=True, upload_to='%Y/%m/%d')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
