# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import recruit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('registered_date', models.DateTimeField(default=recruit.models.change_timezone)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('registered_date', models.DateTimeField(default=recruit.models.change_timezone)),
                ('recruit_count', models.IntegerField()),
                ('attend_count', models.IntegerField(default=1)),
                ('recruit_status', models.IntegerField(choices=[(0, '모집중'), (1, '모집완료')], default='모집중')),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('address3', models.CharField(max_length=100)),
                ('comment_count', models.IntegerField(default=0)),
                ('latlng', models.CharField(blank=True, default='37.497921,127.027636', max_length=50)),
                ('meeting_date', models.DateTimeField(default=recruit.models.change_timezone)),
            ],
            options={
                'ordering': ('-registered_date',),
                'managed': False,
            },
        ),
    ]
