# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-26 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recruit_status',
            field=models.CharField(blank=True, default='s', max_length=1),
        ),
    ]
